CREATE TABLE IF NOT EXISTS person(id INTEGER PRIMARY KEY NOT NULL, firstname VARCHAR(100), lastname VARCHAR(100));
CREATE TABLE IF NOT EXISTS pet(id INTEGER PRIMARY KEY NOT NULL, name VARCHAR(100));
ALTER TABLE person ADD address VARCHAR(100);
ALTER TABLE pet ADD ownerId INTEGER;
